namespace Betfair.Stream.Deserializers;

/// <summary>
/// Enumeration of all known Betfair stream JSON property types for optimized parsing.
/// </summary>
internal enum PropertyType : byte
{
    Unknown = 0,
    Op = 1,
    Id = 2,
    InitialClk = 3,
    Clk = 4,
    Pt = 5,
    Ct = 6,
    Mc = 7,
    Oc = 8,
    StatusCode = 9,
    ErrorCode = 10,
    ConnectionId = 11,
    ConnectionClosed = 12,
    ConnectionsAvailable = 13,
    ConflateMs = 14,
    HeartbeatMs = 15,
    SegmentType = 16,
    MarketDefinition = 17,
    Tv = 18,
    Rc = 19,
    Img = 20,
    Con = 21,
    Ltp = 22,
    Spf = 23,
    Spn = 24,
    Hc = 25,
    Batb = 26,
    Spb = 27,
    Bdatl = 28,
    Trd = 29,
    Atb = 30,
    Spl = 31,
    Atl = 32,
    Batl = 33,
    Bdatb = 34,
    AccountId = 35,
    Closed = 36,
    BspMarket = 37,
    TurnInPlayEnabled = 38,
    PersistenceEnabled = 39,
    MarketBaseRate = 40,
    BettingType = 41,
    Status = 42,
    Venue = 43,
    SettledTime = 44,
    Timezone = 45,
    EachWayDivisor = 46,
    Regulators = 47,
    MarketType = 48,
    NumberOfWinners = 49,
    CountryCode = 50,
    InPlay = 51,
    BetDelay = 52,
    NumberOfActiveRunners = 53,
    EventId = 54,
    CrossMatching = 55,
    RunnersVoidable = 56,
    SuspendTime = 57,
    DiscountAllowed = 58,
    Runners = 59,
    Version = 60,
    EventTypeId = 61,
    Complete = 62,
    OpenDate = 63,
    MarketTime = 64,
    BspReconciled = 65,
    SortPriority = 66,
    RemovalDate = 67,
    AdjustmentFactor = 68,
    Bsp = 69,
    FullImage = 70,
    Ml = 71,
    Mb = 72,
    Uo = 73,
    Orc = 74
}
