name: Mutation Testing with dotnet-stryker

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Install dotnet-stryker
      run: dotnet tool install -g dotnet-stryker

    - name: Run dotnet-stryker
      run: dotnet stryker