name: Mutation Testing with dotnet-stryker

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: src
      run: dotnet restore

    - name: Build
      working-directory: src
      run: dotnet build --no-restore

    - name: Test
      working-directory: src
      run: dotnet test --no-build --verbosity normal

    - name: Install dotnet-stryker
      working-directory: src
      run: dotnet tool install -g dotnet-stryker

    - name: Run dotnet-stryker
      working-directory: src
      run: dotnet stryker --reporter "dashboard" --dashboard-api-key ${{ secrets.STRYKER_DASHBOARD_API_KEY }} --version "master" --verbosity trace