name: Mutation Testing with dotnet-stryker

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build src --no-restore

    - name: Test
      run: dotnet test src --no-build --verbosity normal

    - name: Install dotnet-stryker
      run: dotnet tool install -g dotnet-stryker

    - name: Run dotnet-stryker
      run: cd src && dotnet stryker --reporter "dashboard" --dashboard-api-key ${{ secrets.STRYKER_DASHBOARD_API_KEY }} --project-name "github.com/KelvinVail/Betfair" --version "8.1.0"