name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with dotnet
      run: dotnet build src --configuration Release
    - name: Test
      run: dotnet test src
      # Publish Stream
    - name: publish Betfair.Stream on version change
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/Betfair.Stream/Betfair.Stream.csproj
        TAG_COMMIT: false
        VERSION_REGEX: <Version>(.*)<\/Version>
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    


