name: .NET Core

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - name: Build with dotnet
      run: dotnet build src --configuration Release
    - name: Test
      run: dotnet test src

    - name: publish Betfair.Core on version change
      uses: Jacup/publish-nuget@v2.6.0
      with:
        PROJECT_FILE_PATH: src/Betfair/Betfair.csproj
        TAG_COMMIT: true
        VERSION_REGEX: <Version>(.*)<\/Version>
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    


