name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.3
    - name: Build with dotnet
      run: dotnet build src --configuration Release
    - name: Test
      run: dotnet test src
      # Publish Stream
    - name: Package
      run: dotnet pack -c Release -o . src/Betfair.Stream/Betfair.Stream.csproj
    - name: Publish
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
    


