name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test
      # Publish
    - name: publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Betfair.Identity/Betfair.Identity.csproj # Relative to repository root
        # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
        # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
        # TAG_COMMIT: true # Flag to enable / disalge git tagging
        # TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
        # PACKAGE_NAME: NuGet package name, required when it's different from project name. Defaults to project name
