name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test
      # Publish Identity
    - name: publish Betfair.Identity on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Betfair.Identity/Betfair.Identity.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      # Publish Core
    - name: publish Betfair.Core on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Betfair.Core/Betfair.Core.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      # Publish Stream
    - name: publish Betfair.Stream on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Betfair.Stream/Betfair.Stream.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

