name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.3
    - name: Build with dotnet
      run: dotnet build src --configuration Release
    - name: Test
      run: dotnet test src

      # Publish Core
    - name: publish Betfair.Core on version change
      uses: Jacup/publish-nuget@v2.6.0
      with:
        PROJECT_FILE_PATH: src/Betfair.Core/Betfair.Core.csproj
        TAG_COMMIT: true
        VERSION_REGEX: <Version>(.*)<\/Version>
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      # Publish Stream
    - name: publish Betfair.Stream on version change
      uses: Jacup/publish-nuget@v2.6.0
      with:
        PROJECT_FILE_PATH: src/Betfair.Stream/Betfair.Stream.csproj
        TAG_COMMIT: true
        VERSION_REGEX: <Version>(.*)<\/Version>
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    


